name: xdialog
description: A highly customizable animated dialog package for Flutter with dynamic configurations, multiple button support, and smooth animations.
version: 1.0.0
homepage: https://github.com/yourusername/xdialog
repository: https://github.com/yourusername/xdialog

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true